// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artists.sql

package db

import (
	"context"
)

const getArtistByID = `-- name: GetArtistByID :one
SELECT id, name, deleted_at, created_at, updated_at
FROM artists
WHERE id = ?
  AND deleted_at IS NULL
`

// Get a single artist by ID (excluding soft-deleted)
func (q *Queries) GetArtistByID(ctx context.Context, id int64) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtistByID, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArtists = `-- name: ListArtists :many
SELECT id, name, deleted_at, created_at, updated_at
FROM artists
WHERE deleted_at IS NULL
ORDER BY name
`

// List artists
func (q *Queries) ListArtists(ctx context.Context) ([]Artist, error) {
	rows, err := q.db.QueryContext(ctx, listArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteArtist = `-- name: SoftDeleteArtist :one
UPDATE artists
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = ?
  AND deleted_at IS NULL
RETURNING id, name, deleted_at, created_at, updated_at
`

// Soft delete artist
func (q *Queries) SoftDeleteArtist(ctx context.Context, id int64) (Artist, error) {
	row := q.db.QueryRowContext(ctx, softDeleteArtist, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateArtist = `-- name: UpdateArtist :one
UPDATE artists
SET name = ?
WHERE id = ?
  AND deleted_at IS NULL
RETURNING id, name, deleted_at, created_at, updated_at
`

type UpdateArtistParams struct {
	Name string
	ID   int64
}

// Update artist name
func (q *Queries) UpdateArtist(ctx context.Context, arg UpdateArtistParams) (Artist, error) {
	row := q.db.QueryRowContext(ctx, updateArtist, arg.Name, arg.ID)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
