// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folders.sql

package db

import (
	"context"
)

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (path)
VALUES (?)
RETURNING id, path, deleted_at, created_at, updated_at
`

func (q *Queries) CreateFolder(ctx context.Context, path string) (Folder, error) {
	row := q.db.QueryRowContext(ctx, createFolder, path)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT id, path, deleted_at, created_at, updated_at
FROM folders
WHERE id = ?
`

func (q *Queries) GetFolderByID(ctx context.Context, id int64) (Folder, error) {
	row := q.db.QueryRowContext(ctx, getFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFolders = `-- name: ListFolders :many
SELECT id, path, deleted_at, created_at, updated_at
FROM folders
WHERE deleted_at IS NULL
ORDER BY path
`

func (q *Queries) ListFolders(ctx context.Context) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, listFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreFolder = `-- name: RestoreFolder :exec
UPDATE folders
SET deleted_at = NULL
WHERE id = ? AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreFolder(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, restoreFolder, id)
	return err
}

const softDeleteFolder = `-- name: SoftDeleteFolder :exec
UPDATE folders
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteFolder(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteFolder, id)
	return err
}
