// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folders.sql

package db

import (
	"context"

	dbtypes "bottomley.ian/musicserver/internal/dbtypes"
)

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (path)
VALUES (?)
RETURNING id, path, deleted_at, available, last_seen_at, last_scan_at, last_scan_status, last_scan_error, created_at, updated_at
`

func (q *Queries) CreateFolder(ctx context.Context, path string) (Folder, error) {
	row := q.db.QueryRowContext(ctx, createFolder, path)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.DeletedAt,
		&i.Available,
		&i.LastSeenAt,
		&i.LastScanAt,
		&i.LastScanStatus,
		&i.LastScanError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finishFolderScanError = `-- name: FinishFolderScanError :exec
UPDATE folders
SET
  last_scan_status = 'error',
  last_scan_error = ?,
  last_seen_at = CURRENT_TIMESTAMP,
  available = 1
WHERE id = ?
`

type FinishFolderScanErrorParams struct {
	LastScanError dbtypes.NullString
	ID            int64
}

func (q *Queries) FinishFolderScanError(ctx context.Context, arg FinishFolderScanErrorParams) error {
	_, err := q.db.ExecContext(ctx, finishFolderScanError, arg.LastScanError, arg.ID)
	return err
}

const finishFolderScanOK = `-- name: FinishFolderScanOK :exec
UPDATE folders
SET
  last_scan_status = 'ok',
  last_scan_error = NULL,
  last_seen_at = CURRENT_TIMESTAMP,
  available = 1
WHERE id = ?
`

func (q *Queries) FinishFolderScanOK(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, finishFolderScanOK, id)
	return err
}

const finishFolderScanUnavailable = `-- name: FinishFolderScanUnavailable :exec
UPDATE folders
SET
  last_scan_status = 'skipped_unavailable',
  last_scan_error = ?,
  available = 0
WHERE id = ?
`

type FinishFolderScanUnavailableParams struct {
	LastScanError dbtypes.NullString
	ID            int64
}

func (q *Queries) FinishFolderScanUnavailable(ctx context.Context, arg FinishFolderScanUnavailableParams) error {
	_, err := q.db.ExecContext(ctx, finishFolderScanUnavailable, arg.LastScanError, arg.ID)
	return err
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT id, path, deleted_at, available, last_seen_at, last_scan_at, last_scan_status, last_scan_error, created_at, updated_at
FROM folders
WHERE id = ?
`

func (q *Queries) GetFolderByID(ctx context.Context, id int64) (Folder, error) {
	row := q.db.QueryRowContext(ctx, getFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.DeletedAt,
		&i.Available,
		&i.LastSeenAt,
		&i.LastScanAt,
		&i.LastScanStatus,
		&i.LastScanError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFolders = `-- name: ListFolders :many
SELECT id, path, deleted_at, available, last_seen_at, last_scan_at, last_scan_status, last_scan_error, created_at, updated_at
FROM folders
WHERE deleted_at IS NULL
ORDER BY path
`

func (q *Queries) ListFolders(ctx context.Context) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, listFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.DeletedAt,
			&i.Available,
			&i.LastSeenAt,
			&i.LastScanAt,
			&i.LastScanStatus,
			&i.LastScanError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFolderAvailability = `-- name: SetFolderAvailability :exec
UPDATE folders
SET
  available = ?,
  last_seen_at = CASE WHEN ? = 1 THEN CURRENT_TIMESTAMP ELSE last_seen_at END
WHERE id = ?
`

type SetFolderAvailabilityParams struct {
	Available int64
	Column2   interface{}
	ID        int64
}

func (q *Queries) SetFolderAvailability(ctx context.Context, arg SetFolderAvailabilityParams) error {
	_, err := q.db.ExecContext(ctx, setFolderAvailability, arg.Available, arg.Column2, arg.ID)
	return err
}

const softDeleteFolder = `-- name: SoftDeleteFolder :one
UPDATE folders
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
RETURNING id, path, deleted_at, available, last_seen_at, last_scan_at, last_scan_status, last_scan_error, created_at, updated_at
`

func (q *Queries) SoftDeleteFolder(ctx context.Context, id int64) (Folder, error) {
	row := q.db.QueryRowContext(ctx, softDeleteFolder, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.DeletedAt,
		&i.Available,
		&i.LastSeenAt,
		&i.LastScanAt,
		&i.LastScanStatus,
		&i.LastScanError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const startFolderScan = `-- name: StartFolderScan :one
UPDATE folders
SET
  last_scan_at = CURRENT_TIMESTAMP,
  last_scan_status = 'running',
  last_scan_error = NULL
WHERE id = ?
RETURNING last_scan_at
`

// Start a scan and capture a scan "start time" in DB timestamp format.
// Use the returned last_scan_at value as the scan_start_time passed to MarkMissingTracksForFolder.
func (q *Queries) StartFolderScan(ctx context.Context, id int64) (dbtypes.NullTime, error) {
	row := q.db.QueryRowContext(ctx, startFolderScan, id)
	var last_scan_at dbtypes.NullTime
	err := row.Scan(&last_scan_at)
	return last_scan_at, err
}
