// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	dbtypes "bottomley.ian/musicserver/internal/dbtypes"
)

type Album struct {
	ID        int64
	ArtistID  int64
	Title     string
	DeletedAt dbtypes.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Artist struct {
	ID        int64
	Name      string
	DeletedAt dbtypes.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Folder struct {
	ID             int64
	Path           string
	DeletedAt      dbtypes.NullTime
	Available      int64
	LastSeenAt     dbtypes.NullTime
	LastScanAt     dbtypes.NullTime
	LastScanStatus dbtypes.NullString
	LastScanError  dbtypes.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Track struct {
	ID           int64
	FolderID     int64
	ArtistID     dbtypes.NullInt64
	AlbumID      dbtypes.NullInt64
	RelPath      string
	Filename     string
	Ext          string
	Genre        dbtypes.NullString
	Year         dbtypes.NullInt64
	Rating       dbtypes.NullInt64
	SizeBytes    int64
	LastModified int64
	LastSeenAt   time.Time
	DeletedAt    dbtypes.NullTime
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
