// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Folder struct {
	ID        int64
	Path      string
	DeletedAt interface{}
	CreatedAt time.Time
	UpdatedAt time.Time
}
