// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	dbtypes "bottomley.ian/musicserver/internal/dbtypes"
)

type Album struct {
	ID        int64
	ArtistID  int64
	Title     string
	ImagePath dbtypes.NullString
	DeletedAt dbtypes.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Artist struct {
	ID        int64
	Name      string
	DeletedAt dbtypes.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Folder struct {
	ID             int64
	Path           string
	DeletedAt      dbtypes.NullTime
	Available      int64
	LastSeenAt     dbtypes.NullTime
	LastScanAt     dbtypes.NullTime
	LastScanStatus dbtypes.NullString
	LastScanError  dbtypes.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Journal struct {
	Year          int64
	Month         int64
	Day           int64
	SizeBytes     int64
	Hash          string
	Tags          string
	LastCheckedAt time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type JournalEntry struct {
	ID           int64
	Year         int64
	Month        int64
	Day          int64
	JournalDate  string
	Position     int64
	Title        string
	RawLine      string
	Hash         string
	Body         dbtypes.NullString
	Status       dbtypes.NullString
	Tags         string
	PropertyKeys string
	Type         string
	ScheduledAt  dbtypes.NullString
	DeadlineAt   dbtypes.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Playlist struct {
	ID        int64
	Name      string
	DeletedAt dbtypes.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PlaylistTrack struct {
	ID         int64
	PlaylistID int64
	TrackID    int64
	Position   int64
	DeletedAt  dbtypes.NullTime
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Setting struct {
	Key       string
	Value     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Track struct {
	ID              int64
	FolderID        int64
	ArtistID        dbtypes.NullInt64
	AlbumID         dbtypes.NullInt64
	RelPath         string
	Title           string
	Filename        string
	Ext             string
	Genre           dbtypes.NullString
	Year            dbtypes.NullInt64
	Rating          dbtypes.NullInt64
	ImagePath       dbtypes.NullString
	SizeBytes       int64
	LastModified    int64
	DurationSeconds dbtypes.NullInt64
	LastSeenAt      time.Time
	DeletedAt       dbtypes.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
