// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playlist_tracks.sql

package db

import (
	"context"
	"time"

	dbtypes "bottomley.ian/musicserver/internal/dbtypes"
)

const addPlaylistTrack = `-- name: AddPlaylistTrack :one
INSERT INTO playlist_tracks (playlist_id, track_id, position)
VALUES (?, ?, ?)
ON CONFLICT(playlist_id, track_id) DO UPDATE SET
  position = excluded.position,
  deleted_at = NULL
RETURNING id, playlist_id, track_id, position, deleted_at, created_at, updated_at
`

type AddPlaylistTrackParams struct {
	PlaylistID int64
	TrackID    int64
	Position   int64
}

// Add playlist track (upsert by playlist+track)
func (q *Queries) AddPlaylistTrack(ctx context.Context, arg AddPlaylistTrackParams) (PlaylistTrack, error) {
	row := q.db.QueryRowContext(ctx, addPlaylistTrack, arg.PlaylistID, arg.TrackID, arg.Position)
	var i PlaylistTrack
	err := row.Scan(
		&i.ID,
		&i.PlaylistID,
		&i.TrackID,
		&i.Position,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlaylistTracks = `-- name: ListPlaylistTracks :many
SELECT
  pt.id AS playlist_track_id,
  pt.playlist_id,
  pt.track_id,
  pt.position,
  pt.deleted_at AS playlist_track_deleted_at,
  pt.created_at AS playlist_track_created_at,
  pt.updated_at AS playlist_track_updated_at,

  t.id AS track_row_id,
  t.folder_id,
  t.artist_id,
  t.album_id,
  t.rel_path,
  t.filename,
  t.ext,
  t.genre,
  t.year,
  t.rating,
  t.size_bytes,
  t.last_modified,
  t.last_seen_at,
  t.deleted_at AS track_deleted_at,
  t.created_at AS track_created_at,
  t.updated_at AS track_updated_at
FROM playlist_tracks pt
JOIN tracks t ON t.id = pt.track_id
WHERE pt.playlist_id = ?
  AND pt.deleted_at IS NULL
  AND t.deleted_at IS NULL
ORDER BY pt.position
`

type ListPlaylistTracksRow struct {
	PlaylistTrackID        int64
	PlaylistID             int64
	TrackID                int64
	Position               int64
	PlaylistTrackDeletedAt dbtypes.NullTime
	PlaylistTrackCreatedAt time.Time
	PlaylistTrackUpdatedAt time.Time
	TrackRowID             int64
	FolderID               int64
	ArtistID               dbtypes.NullInt64
	AlbumID                dbtypes.NullInt64
	RelPath                string
	Filename               string
	Ext                    string
	Genre                  dbtypes.NullString
	Year                   dbtypes.NullInt64
	Rating                 dbtypes.NullInt64
	SizeBytes              int64
	LastModified           int64
	LastSeenAt             time.Time
	TrackDeletedAt         dbtypes.NullTime
	TrackCreatedAt         time.Time
	TrackUpdatedAt         time.Time
}

// List playlist tracks with track metadata
func (q *Queries) ListPlaylistTracks(ctx context.Context, playlistID int64) ([]ListPlaylistTracksRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistTracks, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaylistTracksRow
	for rows.Next() {
		var i ListPlaylistTracksRow
		if err := rows.Scan(
			&i.PlaylistTrackID,
			&i.PlaylistID,
			&i.TrackID,
			&i.Position,
			&i.PlaylistTrackDeletedAt,
			&i.PlaylistTrackCreatedAt,
			&i.PlaylistTrackUpdatedAt,
			&i.TrackRowID,
			&i.FolderID,
			&i.ArtistID,
			&i.AlbumID,
			&i.RelPath,
			&i.Filename,
			&i.Ext,
			&i.Genre,
			&i.Year,
			&i.Rating,
			&i.SizeBytes,
			&i.LastModified,
			&i.LastSeenAt,
			&i.TrackDeletedAt,
			&i.TrackCreatedAt,
			&i.TrackUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextPlaylistPosition = `-- name: NextPlaylistPosition :one
SELECT COALESCE(MAX(position), 0) + 1
FROM playlist_tracks
WHERE playlist_id = ?
  AND deleted_at IS NULL
`

// Next position for playlist
func (q *Queries) NextPlaylistPosition(ctx context.Context, playlistID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextPlaylistPosition, playlistID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updatePlaylistTrackPosition = `-- name: UpdatePlaylistTrackPosition :one
UPDATE playlist_tracks
SET position = ?
WHERE id = ?
  AND playlist_id = ?
  AND deleted_at IS NULL
RETURNING id, playlist_id, track_id, position, deleted_at, created_at, updated_at
`

type UpdatePlaylistTrackPositionParams struct {
	Position   int64
	ID         int64
	PlaylistID int64
}

// Update playlist track position
func (q *Queries) UpdatePlaylistTrackPosition(ctx context.Context, arg UpdatePlaylistTrackPositionParams) (PlaylistTrack, error) {
	row := q.db.QueryRowContext(ctx, updatePlaylistTrackPosition, arg.Position, arg.ID, arg.PlaylistID)
	var i PlaylistTrack
	err := row.Scan(
		&i.ID,
		&i.PlaylistID,
		&i.TrackID,
		&i.Position,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
