// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package db

import (
	"context"
)

const createSetting = `-- name: CreateSetting :one
INSERT INTO settings (key, value)
VALUES (?, ?)
RETURNING "key", value, created_at, updated_at
`

type CreateSettingParams struct {
	Key   string
	Value string
}

// Create setting
func (q *Queries) CreateSetting(ctx context.Context, arg CreateSettingParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, createSetting, arg.Key, arg.Value)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSetting = `-- name: DeleteSetting :execrows
DELETE FROM settings
WHERE key = ?
`

// Delete setting
func (q *Queries) DeleteSetting(ctx context.Context, key string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSetting, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSetting = `-- name: GetSetting :one
SELECT "key", value, created_at, updated_at
FROM settings
WHERE key = ?
`

// Get setting by key
func (q *Queries) GetSetting(ctx context.Context, key string) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSettings = `-- name: ListSettings :many
SELECT "key", value, created_at, updated_at
FROM settings
ORDER BY key
`

// List settings
func (q *Queries) ListSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSetting = `-- name: UpdateSetting :one
UPDATE settings
SET value = ?
WHERE key = ?
RETURNING "key", value, created_at, updated_at
`

type UpdateSettingParams struct {
	Value string
	Key   string
}

// Update setting
func (q *Queries) UpdateSetting(ctx context.Context, arg UpdateSettingParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, updateSetting, arg.Value, arg.Key)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
