// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"

	dbtypes "bottomley.ian/musicserver/internal/dbtypes"
)

const createTask = `-- name: CreateTask :one
INSERT INTO journal_entries (
  year,
  month,
  day,
  position,
  title,
  raw_line,
  body,
  status,
  tags,
  type,
  scheduled_at,
  deadline_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, year, month, day, position, title, raw_line, body, status, tags, type, scheduled_at, deadline_at, created_at, updated_at
`

type CreateTaskParams struct {
	Year        int64
	Month       int64
	Day         int64
	Position    int64
	Title       string
	RawLine     string
	Body        dbtypes.NullString
	Status      dbtypes.NullString
	Tags        string
	Type        string
	ScheduledAt dbtypes.NullString
	DeadlineAt  dbtypes.NullString
}

// ---------- journal_entries ----------
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (JournalEntry, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Year,
		arg.Month,
		arg.Day,
		arg.Position,
		arg.Title,
		arg.RawLine,
		arg.Body,
		arg.Status,
		arg.Tags,
		arg.Type,
		arg.ScheduledAt,
		arg.DeadlineAt,
	)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Month,
		&i.Day,
		&i.Position,
		&i.Title,
		&i.RawLine,
		&i.Body,
		&i.Status,
		&i.Tags,
		&i.Type,
		&i.ScheduledAt,
		&i.DeadlineAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTasksByDate = `-- name: DeleteTasksByDate :exec
DELETE FROM journal_entries
WHERE year = ?
  AND month = ?
  AND day = ?
`

type DeleteTasksByDateParams struct {
	Year  int64
	Month int64
	Day   int64
}

func (q *Queries) DeleteTasksByDate(ctx context.Context, arg DeleteTasksByDateParams) error {
	_, err := q.db.ExecContext(ctx, deleteTasksByDate, arg.Year, arg.Month, arg.Day)
	return err
}

const deleteTasksByMonth = `-- name: DeleteTasksByMonth :exec
DELETE FROM journal_entries
WHERE year = ?
  AND month = ?
`

type DeleteTasksByMonthParams struct {
	Year  int64
	Month int64
}

func (q *Queries) DeleteTasksByMonth(ctx context.Context, arg DeleteTasksByMonthParams) error {
	_, err := q.db.ExecContext(ctx, deleteTasksByMonth, arg.Year, arg.Month)
	return err
}

const listNotes = `-- name: ListNotes :many
SELECT id, year, month, day, position, title, raw_line, body, status, tags, type, scheduled_at, deadline_at, created_at, updated_at
FROM journal_entries
WHERE status IS NULL
  AND (?1 IS NULL OR year = ?1)
  AND (?2 IS NULL OR month = ?2)
  AND (?3 IS NULL OR day = ?3)
  AND (
    ?4 IS NULL
    OR EXISTS (
      SELECT 1
      FROM json_each(journal_entries.tags)
      WHERE value = ?4
    )
  )
ORDER BY year DESC, month DESC, day DESC, position ASC
`

type ListNotesParams struct {
	Column1 interface{}
	Column2 interface{}
	Column3 interface{}
	Column4 interface{}
}

func (q *Queries) ListNotes(ctx context.Context, arg ListNotesParams) ([]JournalEntry, error) {
	rows, err := q.db.QueryContext(ctx, listNotes,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalEntry
	for rows.Next() {
		var i JournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.Month,
			&i.Day,
			&i.Position,
			&i.Title,
			&i.RawLine,
			&i.Body,
			&i.Status,
			&i.Tags,
			&i.Type,
			&i.ScheduledAt,
			&i.DeadlineAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, year, month, day, position, title, raw_line, body, status, tags, type, scheduled_at, deadline_at, created_at, updated_at
FROM journal_entries
WHERE status IS NOT NULL
  AND (?1 IS NULL OR year = ?1)
  AND (?2 IS NULL OR month = ?2)
  AND (?5 IS NULL OR day = ?5)
  AND (
    ?3 IS NULL
    OR status IN (SELECT value FROM json_each(?3))
  )
  AND (
    ?4 IS NULL
    OR EXISTS (
      SELECT 1
      FROM json_each(journal_entries.tags)
      WHERE value IN (SELECT value FROM json_each(?4))
    )
  )
ORDER BY year DESC, month DESC, day DESC, position ASC
`

type ListTasksParams struct {
	Column1 interface{}
	Column2 interface{}
	Column3 interface{}
	Column4 interface{}
	Column5 interface{}
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]JournalEntry, error) {
	rows, err := q.db.QueryContext(ctx, listTasks,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalEntry
	for rows.Next() {
		var i JournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.Month,
			&i.Day,
			&i.Position,
			&i.Title,
			&i.RawLine,
			&i.Body,
			&i.Status,
			&i.Tags,
			&i.Type,
			&i.ScheduledAt,
			&i.DeadlineAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
