// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"

	dbtypes "bottomley.ian/musicserver/internal/dbtypes"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
  year,
  month,
  day,
  position,
  title,
  body,
  status,
  scheduled_at,
  deadline_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, year, month, day, position, title, body, status, scheduled_at, deadline_at, created_at, updated_at
`

type CreateTaskParams struct {
	Year        int64
	Month       int64
	Day         int64
	Position    int64
	Title       string
	Body        dbtypes.NullString
	Status      string
	ScheduledAt dbtypes.NullString
	DeadlineAt  dbtypes.NullString
}

// ---------- tasks ----------
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Year,
		arg.Month,
		arg.Day,
		arg.Position,
		arg.Title,
		arg.Body,
		arg.Status,
		arg.ScheduledAt,
		arg.DeadlineAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Month,
		&i.Day,
		&i.Position,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.ScheduledAt,
		&i.DeadlineAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTasksByDate = `-- name: DeleteTasksByDate :exec
DELETE FROM tasks
WHERE year = ?
  AND month = ?
  AND day = ?
`

type DeleteTasksByDateParams struct {
	Year  int64
	Month int64
	Day   int64
}

func (q *Queries) DeleteTasksByDate(ctx context.Context, arg DeleteTasksByDateParams) error {
	_, err := q.db.ExecContext(ctx, deleteTasksByDate, arg.Year, arg.Month, arg.Day)
	return err
}

const deleteTasksByMonth = `-- name: DeleteTasksByMonth :exec
DELETE FROM tasks
WHERE year = ?
  AND month = ?
`

type DeleteTasksByMonthParams struct {
	Year  int64
	Month int64
}

func (q *Queries) DeleteTasksByMonth(ctx context.Context, arg DeleteTasksByMonthParams) error {
	_, err := q.db.ExecContext(ctx, deleteTasksByMonth, arg.Year, arg.Month)
	return err
}

const listTasks = `-- name: ListTasks :many
SELECT id, year, month, day, position, title, body, status, scheduled_at, deadline_at, created_at, updated_at
FROM tasks
ORDER BY year DESC, month DESC, day DESC, position ASC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.Month,
			&i.Day,
			&i.Position,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.ScheduledAt,
			&i.DeadlineAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
