// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"

	dbtypes "bottomley.ian/musicserver/internal/dbtypes"
)

const createJournalEntry = `-- name: CreateJournalEntry :one
INSERT INTO journal_entries (
  year,
  month,
  day,
  journal_date,
  position,
  title,
  raw_line,
  hash,
  body,
  status,
  tags,
  property_keys,
  type,
  scheduled_at,
  deadline_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, year, month, day, journal_date, position, title, raw_line, hash, body, status, tags, property_keys, type, scheduled_at, deadline_at, created_at, updated_at
`

type CreateJournalEntryParams struct {
	Year         int64
	Month        int64
	Day          int64
	JournalDate  string
	Position     int64
	Title        string
	RawLine      string
	Hash         string
	Body         dbtypes.NullString
	Status       dbtypes.NullString
	Tags         string
	PropertyKeys string
	Type         string
	ScheduledAt  dbtypes.NullString
	DeadlineAt   dbtypes.NullString
}

// ---------- journal_entries ----------
func (q *Queries) CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRowContext(ctx, createJournalEntry,
		arg.Year,
		arg.Month,
		arg.Day,
		arg.JournalDate,
		arg.Position,
		arg.Title,
		arg.RawLine,
		arg.Hash,
		arg.Body,
		arg.Status,
		arg.Tags,
		arg.PropertyKeys,
		arg.Type,
		arg.ScheduledAt,
		arg.DeadlineAt,
	)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Month,
		&i.Day,
		&i.JournalDate,
		&i.Position,
		&i.Title,
		&i.RawLine,
		&i.Hash,
		&i.Body,
		&i.Status,
		&i.Tags,
		&i.PropertyKeys,
		&i.Type,
		&i.ScheduledAt,
		&i.DeadlineAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJournalEntriesByDate = `-- name: DeleteJournalEntriesByDate :exec
DELETE FROM journal_entries
WHERE year = ?
  AND month = ?
  AND day = ?
`

type DeleteJournalEntriesByDateParams struct {
	Year  int64
	Month int64
	Day   int64
}

func (q *Queries) DeleteJournalEntriesByDate(ctx context.Context, arg DeleteJournalEntriesByDateParams) error {
	_, err := q.db.ExecContext(ctx, deleteJournalEntriesByDate, arg.Year, arg.Month, arg.Day)
	return err
}

const deleteJournalEntriesByMonth = `-- name: DeleteJournalEntriesByMonth :exec
DELETE FROM journal_entries
WHERE year = ?
  AND month = ?
`

type DeleteJournalEntriesByMonthParams struct {
	Year  int64
	Month int64
}

func (q *Queries) DeleteJournalEntriesByMonth(ctx context.Context, arg DeleteJournalEntriesByMonthParams) error {
	_, err := q.db.ExecContext(ctx, deleteJournalEntriesByMonth, arg.Year, arg.Month)
	return err
}

const getJournalEntryByDateHash = `-- name: GetJournalEntryByDateHash :one
SELECT id, year, month, day, journal_date, position, title, raw_line, hash, body, status, tags, property_keys, type, scheduled_at, deadline_at, created_at, updated_at
FROM journal_entries
WHERE year = ?
  AND month = ?
  AND day = ?
  AND hash = ?
LIMIT 1
`

type GetJournalEntryByDateHashParams struct {
	Year  int64
	Month int64
	Day   int64
	Hash  string
}

func (q *Queries) GetJournalEntryByDateHash(ctx context.Context, arg GetJournalEntryByDateHashParams) (JournalEntry, error) {
	row := q.db.QueryRowContext(ctx, getJournalEntryByDateHash,
		arg.Year,
		arg.Month,
		arg.Day,
		arg.Hash,
	)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Month,
		&i.Day,
		&i.JournalDate,
		&i.Position,
		&i.Title,
		&i.RawLine,
		&i.Hash,
		&i.Body,
		&i.Status,
		&i.Tags,
		&i.PropertyKeys,
		&i.Type,
		&i.ScheduledAt,
		&i.DeadlineAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJournalEntryByDatePosition = `-- name: GetJournalEntryByDatePosition :one
SELECT id, year, month, day, journal_date, position, title, raw_line, hash, body, status, tags, property_keys, type, scheduled_at, deadline_at, created_at, updated_at
FROM journal_entries
WHERE year = ?
  AND month = ?
  AND day = ?
  AND position = ?
LIMIT 1
`

type GetJournalEntryByDatePositionParams struct {
	Year     int64
	Month    int64
	Day      int64
	Position int64
}

func (q *Queries) GetJournalEntryByDatePosition(ctx context.Context, arg GetJournalEntryByDatePositionParams) (JournalEntry, error) {
	row := q.db.QueryRowContext(ctx, getJournalEntryByDatePosition,
		arg.Year,
		arg.Month,
		arg.Day,
		arg.Position,
	)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Month,
		&i.Day,
		&i.JournalDate,
		&i.Position,
		&i.Title,
		&i.RawLine,
		&i.Hash,
		&i.Body,
		&i.Status,
		&i.Tags,
		&i.PropertyKeys,
		&i.Type,
		&i.ScheduledAt,
		&i.DeadlineAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJournalEntries = `-- name: ListJournalEntries :many
SELECT id, year, month, day, journal_date, position, title, raw_line, hash, body, status, tags, property_keys, type, scheduled_at, deadline_at, created_at, updated_at
FROM journal_entries
WHERE (
    ?1 IS NULL
    OR journal_date LIKE ?1
    OR scheduled_at LIKE ?1
    OR deadline_at LIKE ?1
  )
  AND (
    ?2 IS NULL
    OR type = ?2
  )
  AND (
    ?3 IS NULL
    OR status IN (SELECT value FROM json_each(?3))
  )
  AND (
    ?4 IS NULL
    OR EXISTS (
      SELECT 1
      FROM json_each(journal_entries.tags)
      WHERE LOWER(value) IN (SELECT LOWER(value) FROM json_each(?4))
    )
  )
ORDER BY year DESC, month DESC, day DESC, position ASC
`

type ListJournalEntriesParams struct {
	Column1 interface{}
	Column2 interface{}
	Column3 interface{}
	Column4 interface{}
}

func (q *Queries) ListJournalEntries(ctx context.Context, arg ListJournalEntriesParams) ([]JournalEntry, error) {
	rows, err := q.db.QueryContext(ctx, listJournalEntries,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalEntry
	for rows.Next() {
		var i JournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.Month,
			&i.Day,
			&i.JournalDate,
			&i.Position,
			&i.Title,
			&i.RawLine,
			&i.Hash,
			&i.Body,
			&i.Status,
			&i.Tags,
			&i.PropertyKeys,
			&i.Type,
			&i.ScheduledAt,
			&i.DeadlineAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalEntryBodiesByPropertyKey = `-- name: ListJournalEntryBodiesByPropertyKey :many
SELECT body
FROM journal_entries
WHERE EXISTS (
  SELECT 1
  FROM json_each(journal_entries.property_keys)
  WHERE LOWER(value) = LOWER(?)
)
`

func (q *Queries) ListJournalEntryBodiesByPropertyKey(ctx context.Context, lower string) ([]dbtypes.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listJournalEntryBodiesByPropertyKey, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []dbtypes.NullString
	for rows.Next() {
		var body dbtypes.NullString
		if err := rows.Scan(&body); err != nil {
			return nil, err
		}
		items = append(items, body)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalEntryPropertyKeys = `-- name: ListJournalEntryPropertyKeys :many
SELECT property_keys
FROM journal_entries
`

func (q *Queries) ListJournalEntryPropertyKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listJournalEntryPropertyKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var property_keys string
		if err := rows.Scan(&property_keys); err != nil {
			return nil, err
		}
		items = append(items, property_keys)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalEntryTags = `-- name: ListJournalEntryTags :many
SELECT tags
FROM journal_entries
`

func (q *Queries) ListJournalEntryTags(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listJournalEntryTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tags string
		if err := rows.Scan(&tags); err != nil {
			return nil, err
		}
		items = append(items, tags)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
