// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tracks.sql

package db

import (
	"context"
	"time"

	dbtypes "bottomley.ian/musicserver/internal/dbtypes"
)

const getFirstTrackImageForAlbum = `-- name: GetFirstTrackImageForAlbum :one
SELECT image_path
FROM tracks
WHERE album_id = ?
  AND deleted_at IS NULL
  AND image_path IS NOT NULL
ORDER BY id
LIMIT 1
`

// First available track image for an album
func (q *Queries) GetFirstTrackImageForAlbum(ctx context.Context, albumID dbtypes.NullInt64) (dbtypes.NullString, error) {
	row := q.db.QueryRowContext(ctx, getFirstTrackImageForAlbum, albumID)
	var image_path dbtypes.NullString
	err := row.Scan(&image_path)
	return image_path, err
}

const getPlayableTrackPathPartsByID = `-- name: GetPlayableTrackPathPartsByID :one
SELECT
  t.id,
  f.path AS folder_path,
  t.rel_path
FROM tracks t
JOIN folders f ON f.id = t.folder_id
WHERE t.id = ?
  AND t.deleted_at IS NULL
  AND f.deleted_at IS NULL
  AND f.available = 1
`

type GetPlayableTrackPathPartsByIDRow struct {
	ID         int64
	FolderPath string
	RelPath    string
}

// Optional: get absolute path pieces for playback (folder path + rel path)
func (q *Queries) GetPlayableTrackPathPartsByID(ctx context.Context, id int64) (GetPlayableTrackPathPartsByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayableTrackPathPartsByID, id)
	var i GetPlayableTrackPathPartsByIDRow
	err := row.Scan(&i.ID, &i.FolderPath, &i.RelPath)
	return i, err
}

const getTrackByID = `-- name: GetTrackByID :one
SELECT id, folder_id, artist_id, album_id, rel_path, filename, ext, genre, year, rating, image_path, size_bytes, last_modified, last_seen_at, deleted_at, created_at, updated_at
FROM tracks
WHERE id = ?
  AND deleted_at IS NULL
`

// Get a single track by ID (excluding deleted)
func (q *Queries) GetTrackByID(ctx context.Context, id int64) (Track, error) {
	row := q.db.QueryRowContext(ctx, getTrackByID, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.ArtistID,
		&i.AlbumID,
		&i.RelPath,
		&i.Filename,
		&i.Ext,
		&i.Genre,
		&i.Year,
		&i.Rating,
		&i.ImagePath,
		&i.SizeBytes,
		&i.LastModified,
		&i.LastSeenAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrackWithJoins = `-- name: GetTrackWithJoins :one
SELECT
  t.id, t.folder_id, t.artist_id, t.album_id, t.rel_path, t.filename, t.ext, t.genre, t.year, t.rating, t.image_path, t.size_bytes, t.last_modified, t.last_seen_at, t.deleted_at, t.created_at, t.updated_at,
  ar.id, ar.name, ar.deleted_at, ar.created_at, ar.updated_at,
  al.id, al.artist_id, al.title, al.image_path, al.deleted_at, al.created_at, al.updated_at,
  al_ar.id, al_ar.name, al_ar.deleted_at, al_ar.created_at, al_ar.updated_at
FROM tracks t
LEFT JOIN artists ar ON ar.id = t.artist_id
LEFT JOIN albums al ON al.id = t.album_id
LEFT JOIN artists al_ar ON al_ar.id = al.artist_id
WHERE t.id = ?
  AND t.deleted_at IS NULL
`

type GetTrackWithJoinsRow struct {
	Track    Track
	Artist   Artist
	Album    Album
	Artist_2 Artist
}

// Get a single track with artist/album info
func (q *Queries) GetTrackWithJoins(ctx context.Context, id int64) (GetTrackWithJoinsRow, error) {
	row := q.db.QueryRowContext(ctx, getTrackWithJoins, id)
	var i GetTrackWithJoinsRow
	err := row.Scan(
		&i.Track.ID,
		&i.Track.FolderID,
		&i.Track.ArtistID,
		&i.Track.AlbumID,
		&i.Track.RelPath,
		&i.Track.Filename,
		&i.Track.Ext,
		&i.Track.Genre,
		&i.Track.Year,
		&i.Track.Rating,
		&i.Track.ImagePath,
		&i.Track.SizeBytes,
		&i.Track.LastModified,
		&i.Track.LastSeenAt,
		&i.Track.DeletedAt,
		&i.Track.CreatedAt,
		&i.Track.UpdatedAt,
		&i.Artist.ID,
		&i.Artist.Name,
		&i.Artist.DeletedAt,
		&i.Artist.CreatedAt,
		&i.Artist.UpdatedAt,
		&i.Album.ID,
		&i.Album.ArtistID,
		&i.Album.Title,
		&i.Album.ImagePath,
		&i.Album.DeletedAt,
		&i.Album.CreatedAt,
		&i.Album.UpdatedAt,
		&i.Artist_2.ID,
		&i.Artist_2.Name,
		&i.Artist_2.DeletedAt,
		&i.Artist_2.CreatedAt,
		&i.Artist_2.UpdatedAt,
	)
	return i, err
}

const listAllIndexedTracks = `-- name: ListAllIndexedTracks :many
SELECT t.id, t.folder_id, t.artist_id, t.album_id, t.rel_path, t.filename, t.ext, t.genre, t.year, t.rating, t.image_path, t.size_bytes, t.last_modified, t.last_seen_at, t.deleted_at, t.created_at, t.updated_at
FROM tracks t
JOIN folders f ON f.id = t.folder_id
WHERE t.deleted_at IS NULL
  AND f.deleted_at IS NULL
ORDER BY t.rel_path
`

// Include unavailable roots too (for admin/debug UI)
func (q *Queries) ListAllIndexedTracks(ctx context.Context) ([]Track, error) {
	rows, err := q.db.QueryContext(ctx, listAllIndexedTracks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.ArtistID,
			&i.AlbumID,
			&i.RelPath,
			&i.Filename,
			&i.Ext,
			&i.Genre,
			&i.Year,
			&i.Rating,
			&i.ImagePath,
			&i.SizeBytes,
			&i.LastModified,
			&i.LastSeenAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllIndexedTracksWithJoins = `-- name: ListAllIndexedTracksWithJoins :many
SELECT
  t.id, t.folder_id, t.artist_id, t.album_id, t.rel_path, t.filename, t.ext, t.genre, t.year, t.rating, t.image_path, t.size_bytes, t.last_modified, t.last_seen_at, t.deleted_at, t.created_at, t.updated_at,
  ar.id, ar.name, ar.deleted_at, ar.created_at, ar.updated_at,
  al.id, al.artist_id, al.title, al.image_path, al.deleted_at, al.created_at, al.updated_at,
  al_ar.id, al_ar.name, al_ar.deleted_at, al_ar.created_at, al_ar.updated_at
FROM tracks t
JOIN folders f ON f.id = t.folder_id
LEFT JOIN artists ar ON ar.id = t.artist_id
LEFT JOIN albums al ON al.id = t.album_id
LEFT JOIN artists al_ar ON al_ar.id = al.artist_id
WHERE t.deleted_at IS NULL
  AND f.deleted_at IS NULL
ORDER BY t.rel_path
`

type ListAllIndexedTracksWithJoinsRow struct {
	Track    Track
	Artist   Artist
	Album    Album
	Artist_2 Artist
}

// Include unavailable roots too (for admin/debug UI) with artist/album info
func (q *Queries) ListAllIndexedTracksWithJoins(ctx context.Context) ([]ListAllIndexedTracksWithJoinsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllIndexedTracksWithJoins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllIndexedTracksWithJoinsRow
	for rows.Next() {
		var i ListAllIndexedTracksWithJoinsRow
		if err := rows.Scan(
			&i.Track.ID,
			&i.Track.FolderID,
			&i.Track.ArtistID,
			&i.Track.AlbumID,
			&i.Track.RelPath,
			&i.Track.Filename,
			&i.Track.Ext,
			&i.Track.Genre,
			&i.Track.Year,
			&i.Track.Rating,
			&i.Track.ImagePath,
			&i.Track.SizeBytes,
			&i.Track.LastModified,
			&i.Track.LastSeenAt,
			&i.Track.DeletedAt,
			&i.Track.CreatedAt,
			&i.Track.UpdatedAt,
			&i.Artist.ID,
			&i.Artist.Name,
			&i.Artist.DeletedAt,
			&i.Artist.CreatedAt,
			&i.Artist.UpdatedAt,
			&i.Album.ID,
			&i.Album.ArtistID,
			&i.Album.Title,
			&i.Album.ImagePath,
			&i.Album.DeletedAt,
			&i.Album.CreatedAt,
			&i.Album.UpdatedAt,
			&i.Artist_2.ID,
			&i.Artist_2.Name,
			&i.Artist_2.DeletedAt,
			&i.Artist_2.CreatedAt,
			&i.Artist_2.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayableTracks = `-- name: ListPlayableTracks :many
SELECT t.id, t.folder_id, t.artist_id, t.album_id, t.rel_path, t.filename, t.ext, t.genre, t.year, t.rating, t.image_path, t.size_bytes, t.last_modified, t.last_seen_at, t.deleted_at, t.created_at, t.updated_at
FROM tracks t
JOIN folders f ON f.id = t.folder_id
WHERE t.deleted_at IS NULL
  AND f.deleted_at IS NULL
  AND f.available = 1
ORDER BY t.rel_path
`

// Default: list all playable tracks (roots currently available)
func (q *Queries) ListPlayableTracks(ctx context.Context) ([]Track, error) {
	rows, err := q.db.QueryContext(ctx, listPlayableTracks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.ArtistID,
			&i.AlbumID,
			&i.RelPath,
			&i.Filename,
			&i.Ext,
			&i.Genre,
			&i.Year,
			&i.Rating,
			&i.ImagePath,
			&i.SizeBytes,
			&i.LastModified,
			&i.LastSeenAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayableTracksWithJoins = `-- name: ListPlayableTracksWithJoins :many
SELECT
  t.id, t.folder_id, t.artist_id, t.album_id, t.rel_path, t.filename, t.ext, t.genre, t.year, t.rating, t.image_path, t.size_bytes, t.last_modified, t.last_seen_at, t.deleted_at, t.created_at, t.updated_at,
  ar.id, ar.name, ar.deleted_at, ar.created_at, ar.updated_at,
  al.id, al.artist_id, al.title, al.image_path, al.deleted_at, al.created_at, al.updated_at,
  al_ar.id, al_ar.name, al_ar.deleted_at, al_ar.created_at, al_ar.updated_at
FROM tracks t
JOIN folders f ON f.id = t.folder_id
LEFT JOIN artists ar ON ar.id = t.artist_id
LEFT JOIN albums al ON al.id = t.album_id
LEFT JOIN artists al_ar ON al_ar.id = al.artist_id
WHERE t.deleted_at IS NULL
  AND f.deleted_at IS NULL
  AND f.available = 1
ORDER BY t.rel_path
`

type ListPlayableTracksWithJoinsRow struct {
	Track    Track
	Artist   Artist
	Album    Album
	Artist_2 Artist
}

// Default: list all playable tracks with artist/album info (roots currently available)
func (q *Queries) ListPlayableTracksWithJoins(ctx context.Context) ([]ListPlayableTracksWithJoinsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlayableTracksWithJoins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayableTracksWithJoinsRow
	for rows.Next() {
		var i ListPlayableTracksWithJoinsRow
		if err := rows.Scan(
			&i.Track.ID,
			&i.Track.FolderID,
			&i.Track.ArtistID,
			&i.Track.AlbumID,
			&i.Track.RelPath,
			&i.Track.Filename,
			&i.Track.Ext,
			&i.Track.Genre,
			&i.Track.Year,
			&i.Track.Rating,
			&i.Track.ImagePath,
			&i.Track.SizeBytes,
			&i.Track.LastModified,
			&i.Track.LastSeenAt,
			&i.Track.DeletedAt,
			&i.Track.CreatedAt,
			&i.Track.UpdatedAt,
			&i.Artist.ID,
			&i.Artist.Name,
			&i.Artist.DeletedAt,
			&i.Artist.CreatedAt,
			&i.Artist.UpdatedAt,
			&i.Album.ID,
			&i.Album.ArtistID,
			&i.Album.Title,
			&i.Album.ImagePath,
			&i.Album.DeletedAt,
			&i.Album.CreatedAt,
			&i.Album.UpdatedAt,
			&i.Artist_2.ID,
			&i.Artist_2.Name,
			&i.Artist_2.DeletedAt,
			&i.Artist_2.CreatedAt,
			&i.Artist_2.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksForFolder = `-- name: ListTracksForFolder :many
SELECT id, folder_id, artist_id, album_id, rel_path, filename, ext, genre, year, rating, image_path, size_bytes, last_modified, last_seen_at, deleted_at, created_at, updated_at
FROM tracks
WHERE folder_id = ? AND deleted_at IS NULL
ORDER BY rel_path
`

// List tracks for a folder (excluding deleted)
func (q *Queries) ListTracksForFolder(ctx context.Context, folderID int64) ([]Track, error) {
	rows, err := q.db.QueryContext(ctx, listTracksForFolder, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.ArtistID,
			&i.AlbumID,
			&i.RelPath,
			&i.Filename,
			&i.Ext,
			&i.Genre,
			&i.Year,
			&i.Rating,
			&i.ImagePath,
			&i.SizeBytes,
			&i.LastModified,
			&i.LastSeenAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMissingTracksForFolder = `-- name: MarkMissingTracksForFolder :exec
UPDATE tracks
SET deleted_at = CURRENT_TIMESTAMP
WHERE folder_id = ?
  AND deleted_at IS NULL
  AND last_seen_at < ?
`

type MarkMissingTracksForFolderParams struct {
	FolderID   int64
	LastSeenAt time.Time
}

// Mark tracks missing if not seen during this scan pass.
// Pass scan_start_time from StartFolderScan (folders.last_scan_at returned value).
func (q *Queries) MarkMissingTracksForFolder(ctx context.Context, arg MarkMissingTracksForFolderParams) error {
	_, err := q.db.ExecContext(ctx, markMissingTracksForFolder, arg.FolderID, arg.LastSeenAt)
	return err
}

const updateTrackImagePath = `-- name: UpdateTrackImagePath :one
UPDATE tracks
SET image_path = ?
WHERE id = ?
  AND deleted_at IS NULL
RETURNING id, folder_id, artist_id, album_id, rel_path, filename, ext, genre, year, rating, image_path, size_bytes, last_modified, last_seen_at, deleted_at, created_at, updated_at
`

type UpdateTrackImagePathParams struct {
	ImagePath dbtypes.NullString
	ID        int64
}

// Update track image path (only set when provided)
func (q *Queries) UpdateTrackImagePath(ctx context.Context, arg UpdateTrackImagePathParams) (Track, error) {
	row := q.db.QueryRowContext(ctx, updateTrackImagePath, arg.ImagePath, arg.ID)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.ArtistID,
		&i.AlbumID,
		&i.RelPath,
		&i.Filename,
		&i.Ext,
		&i.Genre,
		&i.Year,
		&i.Rating,
		&i.ImagePath,
		&i.SizeBytes,
		&i.LastModified,
		&i.LastSeenAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTrackMetadata = `-- name: UpdateTrackMetadata :one
UPDATE tracks
SET artist_id = ?, album_id = ?, genre = ?, year = ?, image_path = COALESCE(?, image_path)
WHERE id = ?
  AND deleted_at IS NULL
RETURNING id, folder_id, artist_id, album_id, rel_path, filename, ext, genre, year, rating, image_path, size_bytes, last_modified, last_seen_at, deleted_at, created_at, updated_at
`

type UpdateTrackMetadataParams struct {
	ArtistID  dbtypes.NullInt64
	AlbumID   dbtypes.NullInt64
	Genre     dbtypes.NullString
	Year      dbtypes.NullInt64
	ImagePath dbtypes.NullString
	ID        int64
}

// Update track metadata from tags
func (q *Queries) UpdateTrackMetadata(ctx context.Context, arg UpdateTrackMetadataParams) (Track, error) {
	row := q.db.QueryRowContext(ctx, updateTrackMetadata,
		arg.ArtistID,
		arg.AlbumID,
		arg.Genre,
		arg.Year,
		arg.ImagePath,
		arg.ID,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.ArtistID,
		&i.AlbumID,
		&i.RelPath,
		&i.Filename,
		&i.Ext,
		&i.Genre,
		&i.Year,
		&i.Rating,
		&i.ImagePath,
		&i.SizeBytes,
		&i.LastModified,
		&i.LastSeenAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTrackRating = `-- name: UpdateTrackRating :one
UPDATE tracks
SET rating = ?
WHERE id = ?
  AND deleted_at IS NULL
RETURNING id, folder_id, artist_id, album_id, rel_path, filename, ext, genre, year, rating, image_path, size_bytes, last_modified, last_seen_at, deleted_at, created_at, updated_at
`

type UpdateTrackRatingParams struct {
	Rating dbtypes.NullInt64
	ID     int64
}

// Update track rating (nullable)
func (q *Queries) UpdateTrackRating(ctx context.Context, arg UpdateTrackRatingParams) (Track, error) {
	row := q.db.QueryRowContext(ctx, updateTrackRating, arg.Rating, arg.ID)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.ArtistID,
		&i.AlbumID,
		&i.RelPath,
		&i.Filename,
		&i.Ext,
		&i.Genre,
		&i.Year,
		&i.Rating,
		&i.ImagePath,
		&i.SizeBytes,
		&i.LastModified,
		&i.LastSeenAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTrack = `-- name: UpsertTrack :one
INSERT INTO tracks (
  folder_id, rel_path, filename, ext, size_bytes, last_modified, last_seen_at, deleted_at
) VALUES (
  ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, NULL
)
ON CONFLICT(folder_id, rel_path) DO UPDATE SET
  filename      = excluded.filename,
  ext           = excluded.ext,
  size_bytes    = excluded.size_bytes,
  last_modified = excluded.last_modified,
  last_seen_at  = CURRENT_TIMESTAMP,
  deleted_at    = NULL
RETURNING id, folder_id, artist_id, album_id, rel_path, filename, ext, genre, year, rating, image_path, size_bytes, last_modified, last_seen_at, deleted_at, created_at, updated_at
`

type UpsertTrackParams struct {
	FolderID     int64
	RelPath      string
	Filename     string
	Ext          string
	SizeBytes    int64
	LastModified int64
}

// Upsert a track discovered during scan.
// Always bumps last_seen_at to CURRENT_TIMESTAMP.
func (q *Queries) UpsertTrack(ctx context.Context, arg UpsertTrackParams) (Track, error) {
	row := q.db.QueryRowContext(ctx, upsertTrack,
		arg.FolderID,
		arg.RelPath,
		arg.Filename,
		arg.Ext,
		arg.SizeBytes,
		arg.LastModified,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.ArtistID,
		&i.AlbumID,
		&i.RelPath,
		&i.Filename,
		&i.Ext,
		&i.Genre,
		&i.Year,
		&i.Rating,
		&i.ImagePath,
		&i.SizeBytes,
		&i.LastModified,
		&i.LastSeenAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
