// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tracks.sql

package db

import (
	"context"
	"time"

	dbtypes "bottomley.ian/musicserver/internal/dbtypes"
)

const getPlayableTrackPathPartsByID = `-- name: GetPlayableTrackPathPartsByID :one
SELECT
  t.id,
  f.path AS folder_path,
  t.rel_path
FROM tracks t
JOIN folders f ON f.id = t.folder_id
WHERE t.id = ?
  AND t.deleted_at IS NULL
  AND f.deleted_at IS NULL
  AND f.available = 1
`

type GetPlayableTrackPathPartsByIDRow struct {
	ID         int64
	FolderPath string
	RelPath    string
}

// Optional: get absolute path pieces for playback (folder path + rel path)
func (q *Queries) GetPlayableTrackPathPartsByID(ctx context.Context, id int64) (GetPlayableTrackPathPartsByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayableTrackPathPartsByID, id)
	var i GetPlayableTrackPathPartsByIDRow
	err := row.Scan(&i.ID, &i.FolderPath, &i.RelPath)
	return i, err
}

const getTrackByID = `-- name: GetTrackByID :one
SELECT id, folder_id, artist_id, album_id, rel_path, filename, ext, genre, year, rating, size_bytes, last_modified, last_seen_at, deleted_at, created_at, updated_at
FROM tracks
WHERE id = ?
  AND deleted_at IS NULL
`

// Get a single track by ID (excluding deleted)
func (q *Queries) GetTrackByID(ctx context.Context, id int64) (Track, error) {
	row := q.db.QueryRowContext(ctx, getTrackByID, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.ArtistID,
		&i.AlbumID,
		&i.RelPath,
		&i.Filename,
		&i.Ext,
		&i.Genre,
		&i.Year,
		&i.Rating,
		&i.SizeBytes,
		&i.LastModified,
		&i.LastSeenAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllIndexedTracks = `-- name: ListAllIndexedTracks :many
SELECT t.id, t.folder_id, t.artist_id, t.album_id, t.rel_path, t.filename, t.ext, t.genre, t.year, t.rating, t.size_bytes, t.last_modified, t.last_seen_at, t.deleted_at, t.created_at, t.updated_at
FROM tracks t
JOIN folders f ON f.id = t.folder_id
WHERE t.deleted_at IS NULL
  AND f.deleted_at IS NULL
ORDER BY t.rel_path
`

// Include unavailable roots too (for admin/debug UI)
func (q *Queries) ListAllIndexedTracks(ctx context.Context) ([]Track, error) {
	rows, err := q.db.QueryContext(ctx, listAllIndexedTracks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.ArtistID,
			&i.AlbumID,
			&i.RelPath,
			&i.Filename,
			&i.Ext,
			&i.Genre,
			&i.Year,
			&i.Rating,
			&i.SizeBytes,
			&i.LastModified,
			&i.LastSeenAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayableTracks = `-- name: ListPlayableTracks :many
SELECT t.id, t.folder_id, t.artist_id, t.album_id, t.rel_path, t.filename, t.ext, t.genre, t.year, t.rating, t.size_bytes, t.last_modified, t.last_seen_at, t.deleted_at, t.created_at, t.updated_at
FROM tracks t
JOIN folders f ON f.id = t.folder_id
WHERE t.deleted_at IS NULL
  AND f.deleted_at IS NULL
  AND f.available = 1
ORDER BY t.rel_path
`

// Default: list all playable tracks (roots currently available)
func (q *Queries) ListPlayableTracks(ctx context.Context) ([]Track, error) {
	rows, err := q.db.QueryContext(ctx, listPlayableTracks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.ArtistID,
			&i.AlbumID,
			&i.RelPath,
			&i.Filename,
			&i.Ext,
			&i.Genre,
			&i.Year,
			&i.Rating,
			&i.SizeBytes,
			&i.LastModified,
			&i.LastSeenAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksForFolder = `-- name: ListTracksForFolder :many
SELECT id, folder_id, artist_id, album_id, rel_path, filename, ext, genre, year, rating, size_bytes, last_modified, last_seen_at, deleted_at, created_at, updated_at
FROM tracks
WHERE folder_id = ? AND deleted_at IS NULL
ORDER BY rel_path
`

// List tracks for a folder (excluding deleted)
func (q *Queries) ListTracksForFolder(ctx context.Context, folderID int64) ([]Track, error) {
	rows, err := q.db.QueryContext(ctx, listTracksForFolder, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.ArtistID,
			&i.AlbumID,
			&i.RelPath,
			&i.Filename,
			&i.Ext,
			&i.Genre,
			&i.Year,
			&i.Rating,
			&i.SizeBytes,
			&i.LastModified,
			&i.LastSeenAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMissingTracksForFolder = `-- name: MarkMissingTracksForFolder :exec
UPDATE tracks
SET deleted_at = CURRENT_TIMESTAMP
WHERE folder_id = ?
  AND deleted_at IS NULL
  AND last_seen_at < ?
`

type MarkMissingTracksForFolderParams struct {
	FolderID   int64
	LastSeenAt time.Time
}

// Mark tracks missing if not seen during this scan pass.
// Pass scan_start_time from StartFolderScan (folders.last_scan_at returned value).
func (q *Queries) MarkMissingTracksForFolder(ctx context.Context, arg MarkMissingTracksForFolderParams) error {
	_, err := q.db.ExecContext(ctx, markMissingTracksForFolder, arg.FolderID, arg.LastSeenAt)
	return err
}

const updateTrackRating = `-- name: UpdateTrackRating :one
UPDATE tracks
SET rating = ?
WHERE id = ?
  AND deleted_at IS NULL
RETURNING id, folder_id, artist_id, album_id, rel_path, filename, ext, genre, year, rating, size_bytes, last_modified, last_seen_at, deleted_at, created_at, updated_at
`

type UpdateTrackRatingParams struct {
	Rating dbtypes.NullInt64
	ID     int64
}

// Update track rating (nullable)
func (q *Queries) UpdateTrackRating(ctx context.Context, arg UpdateTrackRatingParams) (Track, error) {
	row := q.db.QueryRowContext(ctx, updateTrackRating, arg.Rating, arg.ID)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.ArtistID,
		&i.AlbumID,
		&i.RelPath,
		&i.Filename,
		&i.Ext,
		&i.Genre,
		&i.Year,
		&i.Rating,
		&i.SizeBytes,
		&i.LastModified,
		&i.LastSeenAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTrack = `-- name: UpsertTrack :one
INSERT INTO tracks (
  folder_id, rel_path, filename, ext, size_bytes, last_modified, last_seen_at, deleted_at
) VALUES (
  ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, NULL
)
ON CONFLICT(folder_id, rel_path) DO UPDATE SET
  filename      = excluded.filename,
  ext           = excluded.ext,
  size_bytes    = excluded.size_bytes,
  last_modified = excluded.last_modified,
  last_seen_at  = CURRENT_TIMESTAMP,
  deleted_at    = NULL
RETURNING id, folder_id, artist_id, album_id, rel_path, filename, ext, genre, year, rating, size_bytes, last_modified, last_seen_at, deleted_at, created_at, updated_at
`

type UpsertTrackParams struct {
	FolderID     int64
	RelPath      string
	Filename     string
	Ext          string
	SizeBytes    int64
	LastModified int64
}

// Upsert a track discovered during scan.
// Always bumps last_seen_at to CURRENT_TIMESTAMP.
func (q *Queries) UpsertTrack(ctx context.Context, arg UpsertTrackParams) (Track, error) {
	row := q.db.QueryRowContext(ctx, upsertTrack,
		arg.FolderID,
		arg.RelPath,
		arg.Filename,
		arg.Ext,
		arg.SizeBytes,
		arg.LastModified,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.ArtistID,
		&i.AlbumID,
		&i.RelPath,
		&i.Filename,
		&i.Ext,
		&i.Genre,
		&i.Year,
		&i.Rating,
		&i.SizeBytes,
		&i.LastModified,
		&i.LastSeenAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
